stages:
    - build
    - babel
    - deploy

build:
    stage: build
    script:
     - make
    artifacts:
      paths:
        - shipBuilder/index.html
        - shipBuilder/css
        - shipBuilder/assets
        - shipBuilder/js

build-babel:
    stage: build
    script:
    - cd babel && make

babel:
    stage: babel
    dependencies:
    - build
    script:
    - docker run -t --rm -v `pwd`:/work -w /work -u $(id -u):$(id -g) babel
    - mv shipBuilder/babel-js shipBuilder/js
    artifacts:
      paths:
        - shipBuilder/index.html
        - shipBuilder/css
        - shipBuilder/assets
        - shipBuilder/js

pages:
  stage: deploy
  dependencies:
     - babel
  script:
       - mv shipBuilder/ public/
  artifacts:
        when: on_success
        paths:
        - public
  only:
      - master
