stages:
    - build
    - deploy

build:
    stage: build
    script:
     - make
    artifacts:
      paths:
        - shipBuilder/shipBuilder.html
        - shipBuilder/css
        - shipBuilder/assets
        - shipBuilder/js

pages:
  stage: deploy
  dependencies:
     - build
  script:
       - mv shipBuilder/ public/
       - rm -rf public/index.template.html
  artifacts:
        when: on_success
        paths:
        - public
  only:
      - master
