sudo: required

env:
  global:
    secure: "eBqiHShY2QDAbd5dTCyzE2JYsIuDLGAwM6I/EckdtfcKaEDV/UQ86pIS+o/u0y3t/SWDZAzSgebBUURvQUYSweovaCP5WbUH9vRJZ05c3ow783m83QmS9pup/2GZygGiIHMXTEjA80h0q3vAEjSxQwmfX0nrInCuccaZEas+DYfWBLyUIZ5Ukpf94PxDh6qfiPoRGJGix1Rnn8w6Gbb65L4sRTzYes+zNLFq+K0jXheCXLk7xJS69T9oW26tHn2sDZjyannpsQFuskEvpuSGMHrqQJU8j8pikpTeT7sAEbUKlm0qmJEevXkaHxAXqAh30XpNBtsf9yVUd/h1LR51pv2YOUgDtj3wU92wX/sSSHoZ0OBQsKDcXG3Ui6SseL1Kj91Uv2QTsKeVZWpIhxCSFL9DhB++bFsgZ1d0SIQCa4UOlLY1f+1k77hn+YLWYZuN7VjIAoUwtREP8WrZZWZgyw9zcyl6SAfhAY3kVaZY+78KESh4BLZFr3P0qVa6v9pJWfSIn/gEf8SudebWT3Vh1GvvnYvvn+5GxathTTKvtEw6kWL66YsdKaIrD5Ac8VNjk336B5y6QdZMEXHup9z2zsSAL5xHzCZVTkKP+xBfvz84T9OqfX/rI/YyLYOr9ND8hJyG/z2//sdPW2rm6sdkG40g1P06NXjoWeLBzlKVP6I="

services:
- docker

before_install:
- echo "Before install"

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive

script:
    - make
    - cd babel && make && cd ..
    - cd buildHull && make && cd ..
    - cd rebuildHull && make && cd ..
    - make babel
    - make selenium

after_success:
- |
    echo "SUCCESS!"
    echo "TRAVIS_BRANCH  $TRAVIS_BRANCH"
    echo "TRAVIS_TAG     $TRAVIS_TAG"

# travis setup releases
# https://docs.travis-ci.com/user/deployment
# https://docs.travis-ci.com/user/deployment#conditional-releases-with-on

before_deploy:
- ls -altr shipBuilder/ || true;

# https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: shipBuilder
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

notifications:
email: true

